ACCESS_JWT_KEY: ${ACCESS_JWT_KEY:}
REFRESH_JWT_KEY: ${REFRESH_JWT_KEY:}

spring:
  application:
    name: motung-i-backend

  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - profile
              - email

management:
  metrics:
    tags:
      application: ${spring.application.name:}
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8081

cloud:
  aws:
    s3:
      access-key: ${S3_ACCESS_KEY:}
      secret-key: ${S3_SECRET_KEY:}
      region: ${S3_REGION:}
      bucket-name: ${S3_BUCKET_NAME:}

  open-ai:
    api-key: ${OPEN_AI_API_KEY:}

  youtube:
    api-key: ${YOUTUBE_API_KEY:}

  naver:
    client-id: ${NAVER_CLIENT_ID:}
    client-secret-key: ${NAVER_CLIENT_SECRET_KEY:}

  apple:
    team-id: ${APPLE_TEAM_ID:}
    apple-login-key: ${APPLE_LOGIN_KEY:}
    client-id: ${APPLE_CLIENT_ID:}
    private-key: ${APPLE_PRIVATE_KEY:}

firebase:
  credentials: ${FCM_CONFIG:}

---
spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ACCESS_EXPIRE_TIME: 26297460000 # 10달
REFRESH_EXPIRE_TIME: 315569520000 # 10년

---
spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      cluster:
        nodes: ${REDIS_NODES:}
        max-redirects: 3

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

ACCESS_EXPIRE_TIME: 1800000 # 30분
REFRESH_EXPIRE_TIME: 8640000000 # 100일
